### PR TITLE
Add alt text

### PR DESCRIPTION
**Pull request by vladh**
Will do the same for captions if this is approved.

### CODE REVIEW

**Comment by vladh** [comment]
I do wonder whether it would make sense to make a model for screenshots and put all the fields in there. Having fields like `alt_text` live inside the attachment metadata makes them an odd second-class citizen, whereas a separate model would be more intuitive when reading the code. No big deal either way though.

**Review by tvararu — APPROVED** [review]
Great PR! :100: 

Can you:

- Add `alt: image_alt_text_fallback(image)` to the `image_tag` on the edit screenshots page: https://github.com/design-history/design-history/blob/979a7ba5b1dbba6504640834f2f3ce3b821aaa97/app/views/post_images/index.html.erb#L51
- Rebase and squash your commits into just one; I think this changeset doesn't need more than 1 commit, so include the change above, and there is no need for a "fix linting" one
- Update the commit message in line with the [GDS Way guidance on commits](https://gds-way.cloudapps.digital/standards/source-code/working-with-git.html#commits) [^1]

Pre-approved, can merge after.

[^1]: A short title formatted like an email title (e.g. "Allow editing screenshot alt text") and a brief description of "why" (e.g. "This allows users to make inclusive posts which can be read with screen readers.")

**Comment by tvararu** [comment]
> I do wonder whether it would make sense to make a model for screenshots and put all the fields in there. Having fields like `alt_text` live inside the attachment metadata makes them an odd second-class citizen, whereas a separate model would be more intuitive when reading the code. No big deal either way though.

Definitely this will need to move to a separate model at some point. It's done using `custom_metadata` just to get it out the door, as it was pretty essential functionality.

**Comment by vladh** [comment]
@tvararu Done, thank you for the detailed feedback :)

**Comment by tvararu** [comment]
🙌

**Pull request merged**
