### PR TITLE
Allow users to exclude images from list at bottom of post

### PR DESCRIPTION
**Pull request by tvararu**
This adds a new checkbox to each image, allowing users to opt out of showing certain images at the bottom of a post.

It adds a migration to set `show_at_bottom: "1"` to all existing blobs.

Also renames the section from "Screenshots" to "Images" as that's more appropriate/all-encompassing, as suggested by @adamsilver.

Closes https://github.com/design-history/design-history/issues/320.

### After

image
image
image

### CODE REVIEW

**Comment by adamsilver** [comment]
Boom!

**Comment by adamsilver** [comment]
I would default to off.

**Comment by tvararu** [comment]
@adamsilver updated!

**Comment by fofr** [comment]
I think this default could be a preference.

**Comment by tvararu** [comment]
@fofr I made an issue to track that, as I think we might have a few other things that could be preferences: https://github.com/design-history/design-history/issues/404#issuecomment-1696226605

**Pull request merged**
